# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chesse_backend_api/v1alpha1/chesse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chesse_backend_api.v1alpha1 import (
    games_pb2 as chesse__backend__api_dot_v1alpha1_dot_games__pb2,
)
from chesse_backend_api.v1alpha1 import (
    positions_pb2 as chesse__backend__api_dot_v1alpha1_dot_positions__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="chesse_backend_api/v1alpha1/chesse.proto",
    package="chesse_backend_api.v1alpha1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n(chesse_backend_api/v1alpha1/chesse.proto\x12\x1b\x63hesse_backend_api.v1alpha1\x1a\'chesse_backend_api/v1alpha1/games.proto\x1a+chesse_backend_api/v1alpha1/positions.proto"_\n\x1aGetSimilarPositionsRequest\x12\x41\n\x08position\x18\x01 \x01(\x0b\x32%.chesse_backend_api.v1alpha1.PositionR\x08position"x\n\x1bGetSimilarPositionsResponse\x12Y\n\x11similar_positions\x18\x01 \x03(\x0b\x32,.chesse_backend_api.v1alpha1.SimilarPositionR\x10similarPositions")\n\x0eGetGameRequest\x12\x17\n\x07game_id\x18\x01 \x01(\tR\x06gameId"H\n\x0fGetGameResponse\x12\x35\n\x04game\x18\x01 \x01(\x0b\x32!.chesse_backend_api.v1alpha1.GameR\x04game"T\n\x0fGetGamesRequest\x12\x41\n\x08position\x18\x01 \x01(\x0b\x32%.chesse_backend_api.v1alpha1.PositionR\x08position"\x8d\x01\n\x10GetGamesResponse\x12\x37\n\x05games\x18\x01 \x03(\x0b\x32!.chesse_backend_api.v1alpha1.GameR\x05games\x12@\n\x05stats\x18\x02 \x01(\x0b\x32*.chesse_backend_api.v1alpha1.PositionStatsR\x05stats2\xf0\x02\n\x14\x43heSSEBackendService\x12\x88\x01\n\x13GetSimilarPositions\x12\x37.chesse_backend_api.v1alpha1.GetSimilarPositionsRequest\x1a\x38.chesse_backend_api.v1alpha1.GetSimilarPositionsResponse\x12\x64\n\x07GetGame\x12+.chesse_backend_api.v1alpha1.GetGameRequest\x1a,.chesse_backend_api.v1alpha1.GetGameResponse\x12g\n\x08GetGames\x12,.chesse_backend_api.v1alpha1.GetGamesRequest\x1a-.chesse_backend_api.v1alpha1.GetGamesResponseb\x06proto3',
    dependencies=[
        chesse__backend__api_dot_v1alpha1_dot_games__pb2.DESCRIPTOR,
        chesse__backend__api_dot_v1alpha1_dot_positions__pb2.DESCRIPTOR,
    ],
)


_GETSIMILARPOSITIONSREQUEST = _descriptor.Descriptor(
    name="GetSimilarPositionsRequest",
    full_name="chesse_backend_api.v1alpha1.GetSimilarPositionsRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="position",
            full_name="chesse_backend_api.v1alpha1.GetSimilarPositionsRequest.position",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="position",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=159,
    serialized_end=254,
)


_GETSIMILARPOSITIONSRESPONSE = _descriptor.Descriptor(
    name="GetSimilarPositionsResponse",
    full_name="chesse_backend_api.v1alpha1.GetSimilarPositionsResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="similar_positions",
            full_name="chesse_backend_api.v1alpha1.GetSimilarPositionsResponse.similar_positions",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="similarPositions",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=256,
    serialized_end=376,
)


_GETGAMEREQUEST = _descriptor.Descriptor(
    name="GetGameRequest",
    full_name="chesse_backend_api.v1alpha1.GetGameRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="game_id",
            full_name="chesse_backend_api.v1alpha1.GetGameRequest.game_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="gameId",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=378,
    serialized_end=419,
)


_GETGAMERESPONSE = _descriptor.Descriptor(
    name="GetGameResponse",
    full_name="chesse_backend_api.v1alpha1.GetGameResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="game",
            full_name="chesse_backend_api.v1alpha1.GetGameResponse.game",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="game",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=421,
    serialized_end=493,
)


_GETGAMESREQUEST = _descriptor.Descriptor(
    name="GetGamesRequest",
    full_name="chesse_backend_api.v1alpha1.GetGamesRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="position",
            full_name="chesse_backend_api.v1alpha1.GetGamesRequest.position",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="position",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=495,
    serialized_end=579,
)


_GETGAMESRESPONSE = _descriptor.Descriptor(
    name="GetGamesResponse",
    full_name="chesse_backend_api.v1alpha1.GetGamesResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="games",
            full_name="chesse_backend_api.v1alpha1.GetGamesResponse.games",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="games",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="stats",
            full_name="chesse_backend_api.v1alpha1.GetGamesResponse.stats",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="stats",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=582,
    serialized_end=723,
)

_GETSIMILARPOSITIONSREQUEST.fields_by_name[
    "position"
].message_type = chesse__backend__api_dot_v1alpha1_dot_positions__pb2._POSITION
_GETSIMILARPOSITIONSRESPONSE.fields_by_name[
    "similar_positions"
].message_type = chesse__backend__api_dot_v1alpha1_dot_positions__pb2._SIMILARPOSITION
_GETGAMERESPONSE.fields_by_name[
    "game"
].message_type = chesse__backend__api_dot_v1alpha1_dot_games__pb2._GAME
_GETGAMESREQUEST.fields_by_name[
    "position"
].message_type = chesse__backend__api_dot_v1alpha1_dot_positions__pb2._POSITION
_GETGAMESRESPONSE.fields_by_name[
    "games"
].message_type = chesse__backend__api_dot_v1alpha1_dot_games__pb2._GAME
_GETGAMESRESPONSE.fields_by_name[
    "stats"
].message_type = chesse__backend__api_dot_v1alpha1_dot_positions__pb2._POSITIONSTATS
DESCRIPTOR.message_types_by_name["GetSimilarPositionsRequest"] = _GETSIMILARPOSITIONSREQUEST
DESCRIPTOR.message_types_by_name["GetSimilarPositionsResponse"] = _GETSIMILARPOSITIONSRESPONSE
DESCRIPTOR.message_types_by_name["GetGameRequest"] = _GETGAMEREQUEST
DESCRIPTOR.message_types_by_name["GetGameResponse"] = _GETGAMERESPONSE
DESCRIPTOR.message_types_by_name["GetGamesRequest"] = _GETGAMESREQUEST
DESCRIPTOR.message_types_by_name["GetGamesResponse"] = _GETGAMESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSimilarPositionsRequest = _reflection.GeneratedProtocolMessageType(
    "GetSimilarPositionsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETSIMILARPOSITIONSREQUEST,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetSimilarPositionsRequest)
    },
)
_sym_db.RegisterMessage(GetSimilarPositionsRequest)

GetSimilarPositionsResponse = _reflection.GeneratedProtocolMessageType(
    "GetSimilarPositionsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETSIMILARPOSITIONSRESPONSE,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetSimilarPositionsResponse)
    },
)
_sym_db.RegisterMessage(GetSimilarPositionsResponse)

GetGameRequest = _reflection.GeneratedProtocolMessageType(
    "GetGameRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETGAMEREQUEST,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetGameRequest)
    },
)
_sym_db.RegisterMessage(GetGameRequest)

GetGameResponse = _reflection.GeneratedProtocolMessageType(
    "GetGameResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETGAMERESPONSE,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetGameResponse)
    },
)
_sym_db.RegisterMessage(GetGameResponse)

GetGamesRequest = _reflection.GeneratedProtocolMessageType(
    "GetGamesRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETGAMESREQUEST,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetGamesRequest)
    },
)
_sym_db.RegisterMessage(GetGamesRequest)

GetGamesResponse = _reflection.GeneratedProtocolMessageType(
    "GetGamesResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETGAMESRESPONSE,
        "__module__": "chesse_backend_api.v1alpha1.chesse_pb2"
        # @@protoc_insertion_point(class_scope:chesse_backend_api.v1alpha1.GetGamesResponse)
    },
)
_sym_db.RegisterMessage(GetGamesResponse)


_CHESSEBACKENDSERVICE = _descriptor.ServiceDescriptor(
    name="CheSSEBackendService",
    full_name="chesse_backend_api.v1alpha1.CheSSEBackendService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=726,
    serialized_end=1094,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetSimilarPositions",
            full_name="chesse_backend_api.v1alpha1.CheSSEBackendService.GetSimilarPositions",
            index=0,
            containing_service=None,
            input_type=_GETSIMILARPOSITIONSREQUEST,
            output_type=_GETSIMILARPOSITIONSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetGame",
            full_name="chesse_backend_api.v1alpha1.CheSSEBackendService.GetGame",
            index=1,
            containing_service=None,
            input_type=_GETGAMEREQUEST,
            output_type=_GETGAMERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="GetGames",
            full_name="chesse_backend_api.v1alpha1.CheSSEBackendService.GetGames",
            index=2,
            containing_service=None,
            input_type=_GETGAMESREQUEST,
            output_type=_GETGAMESRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CHESSEBACKENDSERVICE)

DESCRIPTOR.services_by_name["CheSSEBackendService"] = _CHESSEBACKENDSERVICE

# @@protoc_insertion_point(module_scope)
