repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      # sort imports
      - id: isort
        args: ["--profile", "black"] 
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      # code formatter
      - id: black 
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      # checks style irregularities missed by black
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # checks docstring come before implementation
      - id: check-docstring-first 
      # ensures that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
      # checks JSON files for parseable syntax
      - id: check-json
      # checks toml files for parseable syntax
      - id: check-toml
      # detects the presence of private keys
      - id: detect-private-key
      # ensures that a file is either empty, or ends with one newline
      - id: end-of-file-fixer
      # formats JSON
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--indent", "4"]
      # sorts requirements.txt contents
      - id: requirements-txt-fixer
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      # formats docstrings
      - id: docformatter
        args: [--in-place]
