# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from duchess_backend_api.v1alpha1 import (
    games_pb2 as duchess__backend__api_dot_v1alpha1_dot_games__pb2,
)


class DuchessBackendServiceStub(object):
    """Duchess Backend Service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSimilarGames = channel.unary_unary(
            "/duchess_backend_api.v1alpha1.DuchessBackendService/GetSimilarGames",
            request_serializer=duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesRequest.SerializeToString,
            response_deserializer=duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesResponse.FromString,
        )


class DuchessBackendServiceServicer(object):
    """Duchess Backend Service."""

    def GetSimilarGames(self, request, context):
        """Fetch a collection of games."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DuchessBackendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetSimilarGames": grpc.unary_unary_rpc_method_handler(
            servicer.GetSimilarGames,
            request_deserializer=duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesRequest.FromString,
            response_serializer=duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "duchess_backend_api.v1alpha1.DuchessBackendService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DuchessBackendService(object):
    """Duchess Backend Service."""

    @staticmethod
    def GetSimilarGames(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/duchess_backend_api.v1alpha1.DuchessBackendService/GetSimilarGames",
            duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesRequest.SerializeToString,
            duchess__backend__api_dot_v1alpha1_dot_games__pb2.GetSimilarGamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
