# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duchess_backend_api/v1alpha1/games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from duchess_backend_api.v1alpha1 import (
    positions_pb2 as duchess__backend__api_dot_v1alpha1_dot_positions__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="duchess_backend_api/v1alpha1/games.proto",
    package="duchess_backend_api.v1alpha1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n(duchess_backend_api/v1alpha1/games.proto\x12\x1c\x64uchess_backend_api.v1alpha1\x1a,duchess_backend_api/v1alpha1/positions.proto"Z\n\x04Game\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x42\n\x08position\x18\x02 \x01(\x0b\x32&.duchess_backend_api.v1alpha1.PositionR\x08position";\n\x16GetSimilarGamesRequest\x12!\n\x0cposition_fen\x18\x01 \x01(\tR\x0bpositionFen"S\n\x17GetSimilarGamesResponse\x12\x38\n\x05games\x18\x01 \x03(\x0b\x32".duchess_backend_api.v1alpha1.GameR\x05gamesb\x06proto3',
    dependencies=[
        duchess__backend__api_dot_v1alpha1_dot_positions__pb2.DESCRIPTOR,
    ],
)


_GAME = _descriptor.Descriptor(
    name="Game",
    full_name="duchess_backend_api.v1alpha1.Game",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="duchess_backend_api.v1alpha1.Game.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="id",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="position",
            full_name="duchess_backend_api.v1alpha1.Game.position",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="position",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=120,
    serialized_end=210,
)


_GETSIMILARGAMESREQUEST = _descriptor.Descriptor(
    name="GetSimilarGamesRequest",
    full_name="duchess_backend_api.v1alpha1.GetSimilarGamesRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="position_fen",
            full_name="duchess_backend_api.v1alpha1.GetSimilarGamesRequest.position_fen",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="positionFen",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=212,
    serialized_end=271,
)


_GETSIMILARGAMESRESPONSE = _descriptor.Descriptor(
    name="GetSimilarGamesResponse",
    full_name="duchess_backend_api.v1alpha1.GetSimilarGamesResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="games",
            full_name="duchess_backend_api.v1alpha1.GetSimilarGamesResponse.games",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="games",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=273,
    serialized_end=356,
)

_GAME.fields_by_name[
    "position"
].message_type = duchess__backend__api_dot_v1alpha1_dot_positions__pb2._POSITION
_GETSIMILARGAMESRESPONSE.fields_by_name["games"].message_type = _GAME
DESCRIPTOR.message_types_by_name["Game"] = _GAME
DESCRIPTOR.message_types_by_name["GetSimilarGamesRequest"] = _GETSIMILARGAMESREQUEST
DESCRIPTOR.message_types_by_name["GetSimilarGamesResponse"] = _GETSIMILARGAMESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Game = _reflection.GeneratedProtocolMessageType(
    "Game",
    (_message.Message,),
    {
        "DESCRIPTOR": _GAME,
        "__module__": "duchess_backend_api.v1alpha1.games_pb2"
        # @@protoc_insertion_point(class_scope:duchess_backend_api.v1alpha1.Game)
    },
)
_sym_db.RegisterMessage(Game)

GetSimilarGamesRequest = _reflection.GeneratedProtocolMessageType(
    "GetSimilarGamesRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETSIMILARGAMESREQUEST,
        "__module__": "duchess_backend_api.v1alpha1.games_pb2"
        # @@protoc_insertion_point(class_scope:duchess_backend_api.v1alpha1.GetSimilarGamesRequest)
    },
)
_sym_db.RegisterMessage(GetSimilarGamesRequest)

GetSimilarGamesResponse = _reflection.GeneratedProtocolMessageType(
    "GetSimilarGamesResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETSIMILARGAMESRESPONSE,
        "__module__": "duchess_backend_api.v1alpha1.games_pb2"
        # @@protoc_insertion_point(class_scope:duchess_backend_api.v1alpha1.GetSimilarGamesResponse)
    },
)
_sym_db.RegisterMessage(GetSimilarGamesResponse)


# @@protoc_insertion_point(module_scope)
