# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: duchess_backend_api/v1alpha1/positions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="duchess_backend_api/v1alpha1/positions.proto",
    package="duchess_backend_api.v1alpha1",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n,duchess_backend_api/v1alpha1/positions.proto\x12\x1c\x64uchess_backend_api.v1alpha1"\x1c\n\x08Position\x12\x10\n\x03\x66\x65n\x18\x01 \x01(\tR\x03\x66\x65nb\x06proto3',
)


_POSITION = _descriptor.Descriptor(
    name="Position",
    full_name="duchess_backend_api.v1alpha1.Position",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="fen",
            full_name="duchess_backend_api.v1alpha1.Position.fen",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            json_name="fen",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=106,
)

DESCRIPTOR.message_types_by_name["Position"] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType(
    "Position",
    (_message.Message,),
    {
        "DESCRIPTOR": _POSITION,
        "__module__": "duchess_backend_api.v1alpha1.positions_pb2"
        # @@protoc_insertion_point(class_scope:duchess_backend_api.v1alpha1.Position)
    },
)
_sym_db.RegisterMessage(Position)


# @@protoc_insertion_point(module_scope)
