import chess
import pytest
from src.encoding import naive_encoding


@pytest.mark.parametrize(
    "board, expected_encoding",
    [
        pytest.param(
            chess.Board(fen="r1bqk1nr/pp1n1ppp/4p3/2b5/4p3/2P1B3/PP1N1PPP/R2QKBNR w KQkq - 0 1"),
            {
                "Ke1",
                "Qd1",
                "Ra1",
                "Rh1",
                "Be3",
                "Bf1",
                "Nd2",
                "Ng1",
                "Pa2",
                "Pb2",
                "Pc3",
                "Pf2",
                "Pg2",
                "Ph2",
                "ke8",
                "qd8",
                "ra8",
                "rh8",
                "bc5",
                "bc8",
                "nd7",
                "ng8",
                "pa7",
                "pb7",
                "pe4",
                "pe6",
                "pf7",
                "pg7",
                "ph7",
            },
            id="Opening",
        ),
        pytest.param(
            chess.Board(fen="rr4k1/2qbpp2/1n1p1b1p/p2P2p1/2pP1PP1/Q1N4P/PPP1RBB1/2K1R3 w - -"),
            {
                "Kc1",
                "Qa3",
                "Re1",
                "Re2",
                "Bf2",
                "Bg2",
                "Nc3",
                "Pa2",
                "Pb2",
                "Pc2",
                "Pd4",
                "Pd5",
                "Pf4",
                "Pg4",
                "Ph3",
                "kg8",
                "qc7",
                "ra8",
                "rb8",
                "bd7",
                "bf6",
                "nb6",
                "pa5",
                "pc4",
                "pd6",
                "pe7",
                "pf7",
                "pg5",
                "ph6",
            },
            id="Middle game",
        ),
        pytest.param(
            chess.Board(fen="1R1R4/p4pp1/4pk2/2pb1P2/r5Pp/2PK3P/2P5/8 w - - 0 1"),
            {
                "Kd3",
                "Rb8",
                "Rd8",
                "Pc2",
                "Pc3",
                "Pf5",
                "Pg4",
                "Ph3",
                "kf6",
                "ra4",
                "bd5",
                "pa7",
                "pc5",
                "pe6",
                "pf7",
                "pg7",
                "ph4",
            },
            id="Endgame",
        ),
    ],
)
def test_get_naive_encoding(board, expected_encoding):
    assert naive_encoding.encode(board) == expected_encoding
