// source: duchess_backend_api/v1alpha1/games.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var duchess_backend_api_v1alpha1_positions_pb = require('../../duchess_backend_api/v1alpha1/positions_pb.js');
goog.object.extend(proto, duchess_backend_api_v1alpha1_positions_pb);
goog.exportSymbol('proto.duchess_backend_api.v1alpha1.Game', null, global);
goog.exportSymbol('proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest', null, global);
goog.exportSymbol('proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.duchess_backend_api.v1alpha1.Game = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.duchess_backend_api.v1alpha1.Game, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.duchess_backend_api.v1alpha1.Game.displayName = 'proto.duchess_backend_api.v1alpha1.Game';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.displayName = 'proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.repeatedFields_, null);
};
goog.inherits(proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.displayName = 'proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.toObject = function(opt_includeInstance) {
  return proto.duchess_backend_api.v1alpha1.Game.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.duchess_backend_api.v1alpha1.Game} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.Game.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    position: (f = msg.getPosition()) && duchess_backend_api_v1alpha1_positions_pb.Position.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.duchess_backend_api.v1alpha1.Game}
 */
proto.duchess_backend_api.v1alpha1.Game.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.duchess_backend_api.v1alpha1.Game;
  return proto.duchess_backend_api.v1alpha1.Game.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.duchess_backend_api.v1alpha1.Game} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.duchess_backend_api.v1alpha1.Game}
 */
proto.duchess_backend_api.v1alpha1.Game.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new duchess_backend_api_v1alpha1_positions_pb.Position;
      reader.readMessage(value,duchess_backend_api_v1alpha1_positions_pb.Position.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.duchess_backend_api.v1alpha1.Game.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.duchess_backend_api.v1alpha1.Game} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.Game.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      duchess_backend_api_v1alpha1_positions_pb.Position.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.duchess_backend_api.v1alpha1.Game} returns this
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Position position = 2;
 * @return {?proto.duchess_backend_api.v1alpha1.Position}
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.getPosition = function() {
  return /** @type{?proto.duchess_backend_api.v1alpha1.Position} */ (
    jspb.Message.getWrapperField(this, duchess_backend_api_v1alpha1_positions_pb.Position, 2));
};


/**
 * @param {?proto.duchess_backend_api.v1alpha1.Position|undefined} value
 * @return {!proto.duchess_backend_api.v1alpha1.Game} returns this
*/
proto.duchess_backend_api.v1alpha1.Game.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.duchess_backend_api.v1alpha1.Game} returns this
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.duchess_backend_api.v1alpha1.Game.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    positionFen: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest;
  return proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPositionFen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPositionFen();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string position_fen = 1;
 * @return {string}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.prototype.getPositionFen = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest} returns this
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesRequest.prototype.setPositionFen = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    gamesList: jspb.Message.toObjectList(msg.getGamesList(),
    proto.duchess_backend_api.v1alpha1.Game.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse;
  return proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.duchess_backend_api.v1alpha1.Game;
      reader.readMessage(value,proto.duchess_backend_api.v1alpha1.Game.deserializeBinaryFromReader);
      msg.addGames(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGamesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.duchess_backend_api.v1alpha1.Game.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Game games = 1;
 * @return {!Array<!proto.duchess_backend_api.v1alpha1.Game>}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.getGamesList = function() {
  return /** @type{!Array<!proto.duchess_backend_api.v1alpha1.Game>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.duchess_backend_api.v1alpha1.Game, 1));
};


/**
 * @param {!Array<!proto.duchess_backend_api.v1alpha1.Game>} value
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse} returns this
*/
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.setGamesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.duchess_backend_api.v1alpha1.Game=} opt_value
 * @param {number=} opt_index
 * @return {!proto.duchess_backend_api.v1alpha1.Game}
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.addGames = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.duchess_backend_api.v1alpha1.Game, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse} returns this
 */
proto.duchess_backend_api.v1alpha1.GetSimilarGamesResponse.prototype.clearGamesList = function() {
  return this.setGamesList([]);
};


goog.object.extend(exports, proto.duchess_backend_api.v1alpha1);
